# a mybinder.org-ready environment for demoing jupyterlab-qzv
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyterlab-qzv-demo
#
name: jupyterlab-qzv-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python=3.10
  - r-shinydashboard

  # labextension build dependencies
  # Fix binder
  - pip:
    - git+https://github.com/yamaton/jupyterlab-qzv
